import React from 'react';
import { PublicNavbar } from './PublicNavbar';
import { Zap, Globe, Lock, Code, Database, Server, Layers, FileSearch } from 'lucide-react';

interface FeaturesPageProps {
  onNavigate: (page: 'home' | 'about' | 'features' | 'contact' | 'login') => void;
}

export const FeaturesPage: React.FC<FeaturesPageProps> = ({ onNavigate }) => {
  const features = [
    {
        icon: Zap,
        title: "AI Logic Reasoning",
        desc: "Unlike regex scanners, our engine understands business logic. It can detect broken access controls (IDOR) and logic flaws."
    },
    {
        icon: Globe,
        title: "Deep Crawling",
        desc: "Executes JavaScript to find hidden routes in Single Page Applications (React, Vue, Angular) that other crawlers miss."
    },
    {
        icon: Database,
        title: "Advanced SQLi",
        desc: "Detects blind, time-based, and error-based SQL injection with auto-generated bypass payloads for WAFs."
    },
    {
        icon: Code,
        title: "Source Code Analysis",
        desc: "Paste your snippet. We analyze syntax trees (AST) to find insecure functions, hardcoded secrets, and logic bombs."
    },
    {
        icon: Lock,
        title: "Auth Testing",
        desc: "Validates JWT signatures, session entropy, cookie security flags, and weak password policies automatically."
    },
    {
        icon: Server,
        title: "Infrastructure",
        desc: "Scans for open ports, outdated server software, SSL/TLS misconfigurations, and dangerous HTTP methods."
    },
    {
        icon: Layers,
        title: "Tech Stack Detect",
        desc: "Fingerprints over 5,000 technologies to identify outdated libraries with known CVEs (Software Composition Analysis)."
    },
    {
        icon: FileSearch,
        title: "Smart Reporting",
        desc: "Generates developer-friendly reports with exact file paths, code snippets, and copy-paste remediation code."
    }
  ];

  return (
    <div className="min-h-screen bg-cyber-bg text-cyber-text-main font-sans relative overflow-hidden flex flex-col">
      <div className="absolute inset-0 bg-grid-pattern opacity-[0.05] pointer-events-none"></div>
      <PublicNavbar current="features" onNavigate={onNavigate} />

      <main className="flex-1 relative z-10 px-6 py-20 max-w-7xl mx-auto w-full">
        <div className="text-center mb-16 animate-fade-in-up">
            <div className="inline-flex items-center gap-2 px-3 py-1 rounded-full bg-cyber-card border border-cyber-border text-cyber-primary text-xs font-bold uppercase tracking-widest mb-6 shadow-soft">
                 Engine Capabilities
            </div>
            <h1 className="text-4xl md:text-5xl font-display font-bold mb-6">Full Spectrum Coverage</h1>
            <p className="text-xl text-cyber-text-secondary max-w-3xl mx-auto leading-relaxed">
                From simple XSS to complex Business Logic flaws, WebSec-AI covers the entire attack surface.
            </p>
        </div>

        <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-6 animate-fade-in-up delay-100">
            {features.map((f, i) => (
                <div key={i} className="cyber-card p-6 hover:bg-cyber-cardHighlight transition-colors group">
                    <div className="w-12 h-12 bg-cyber-bg border border-cyber-border rounded-xl flex items-center justify-center mb-4 text-cyber-text-secondary group-hover:text-cyber-primary group-hover:border-cyber-primary/50 transition-all">
                        <f.icon size={24} />
                    </div>
                    <h3 className="text-lg font-bold mb-2 font-display text-cyber-text-main">{f.title}</h3>
                    <p className="text-sm text-cyber-text-secondary leading-relaxed">
                        {f.desc}
                    </p>
                </div>
            ))}
        </div>
      </main>

      <footer className="py-8 text-center text-cyber-text-muted text-sm border-t border-cyber-border relative z-10 bg-cyber-bg">
        <p>© 2024 WebSec AI. All systems nominal.</p>
      </footer>
    </div>
  );
};